apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: site-app-subdomain
  namespace: site-endpoint
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /app
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/app-root: /app
spec:
  rules:
  - host: app.site.com
    http:
      paths:
      - path: /app
        backend:
          serviceName: site-endpoint
          servicePort: 80
  tls:
  - hosts:
    - app.site.com
    secretName: site-wildcard

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: site-app-subdomain-dist
  namespace: site-endpoint
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /dist/
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: app.site.com
    http:
      paths:
      - path: /dist/
        backend:
          serviceName: site-endpoint
          servicePort: 80
  tls:
  - hosts:
    - app.site.com
    secretName: site-wildcard
