apiVersion: v1
kind: Endpoints
metadata:
  name: site-endpoint
  namespace: site-endpoint
subsets:
- addresses:
  - ip: 1.1.1.1
  - ip: 2.2.2.2
  ports:
  - port: 80
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: site-endpoint
  namespace: site-endpoint
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
